services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=inflan_db;Username=postgres;Password=postgres123
    volumes:
      - ./wwwroot:/app/wwwroot
    networks:
      - inflan-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: inflan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inflan-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - inflan-network
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  inflan-network:
    driver: bridge