services:
  - type: web
    name: dartford-api
    repo: https://github.com/asifraza1013/dartford_backend
    branch: master
    runtime: docker
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/dartford_api.dll
    envVars:
      - key: PORT
        value: 10000
