// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using inflan_api.MyDBContext;

#nullable disable

namespace inflan_api.Migrations
{
    [DbContext(typeof(InflanDBContext))]
    [Migration("20251223120000_AddPaymentModule")]
    partial class AddPaymentModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("inflan_api.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutProject")
                        .HasColumnType("text");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CampaignEndDate")
                        .HasColumnType("date");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text");

                    b.Property<DateOnly>("CampaignStartDate")
                        .HasColumnType("date");

                    b.Property<int>("CampaignStatus")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ContentFiles")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ContractSignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedContractPdfPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InfluencerAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InfluencerId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("InstructionDocuments")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsRecurringEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("PaidAmountInPence")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaymentCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReleasedToInfluencerInPence")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SignatureApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignedContractPdfPath")
                        .HasColumnType("text");

                    b.Property<long>("TotalAmountInPence")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("InfluencerId");

                    b.HasIndex("PlanId");

                    b.ToTable("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
