namespace dartford_api.Utils;

public enum Message
{
    EMAIL_ALREADY_REGISTERED = 4001,
    INVALID_EMAIL_PASSWORD = 4002,
    USER_NOT_FOUND = 4003,
    INFLUENCER_NOT_FOUND = 4004,
    INFLUENCER_NOT_IN_USER_TABLE = 4005,
    
    INFLUENCER_USER_UPDATE_FAILED  = 5001,
    INFLUENCER_DELETE_FAILED  = 5002,
    INFLUENCER_UPDATE_FAILED  = 5003,
    INFLUENCER_USER_DELETE_FAILED  = 5004,
    USER_UPDATE_FAILED  = 5005,
    USER_DELETE_FAILED  = 5006,
    
    USER_CREATED_SUCCESSFULLY = 7001,
    INFLUENCER_CREATED_SUCCESSFULLY = 7002,
    
    
    
}